apiVersion: v1
kind: Pod
metadata:
  name: copy-pod
spec:
  containers:
  - name: copy-container
    image: busybox
    volumeMounts:
    - name: model-volume
      mountPath: /model
    command: ["sleep", "3600"]
  volumes:
  - name: model-volume
    persistentVolumeClaim:
      claimName: my-model-pv
