apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- namespace.yaml
- dolly-devapp.yaml
- pvc_dev.yaml
patches:
- path: dev-namespace.yaml
  target:
    kind: Namespace
    name: dev-namespace
- path: env_patch.yaml
- path: pvc_dev.yaml
