apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-model-pv
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: azurefile-csi-premium
  
