name: Auto Merge

on:
  pull_request:
    types: [labeled]

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'automerge'
    steps:
    - name: Merge pull request
      uses: pascalgn/automerge-action@v0.13.1
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        MERGE_METHOD: squash
        MERGE_LABELS: "automerge,!work in progress"
        UPDATE_LABELS: "automerge"
        MERGE_FILTER_AUTHOR: ""
        MERGE_RETRIES: "6"
        MERGE_RETRY_SLEEP: "10000"
        MERGE_DELETE_BRANCH: "true"
